language: php

php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $PHPCS = 1 ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

notifications:
  email: false